package com.amazon.ask.kair.share.translations;

public class SpanishMXMessages {
    public static final String WELCOME = "Bienvenido al monitoreo de la calidad del aire, ATENCION, Actualmente hay una alerta sanitaria internacional debido al nuevo coronavirus, esto no influye en la calidad del aire, pero se recomienda evitar realizar actividades al aire libre y mantener su sana distancia, para continuar, puedes decirme cuál es tu ciudad.";
    public static final String HELP = "Hola, para poder usar esta skill solo necesita mencionar tu ciudad y buscare las estaciones de monitoreo aire más cercanas y te diré el nivel de contaminación del aire, puedes decirme cuál es tu ciudad.";
    public static final String FALLBACK = "Lo siento, No entendí, ¡Puedes intentar diciendo ayuda!";
    public static final String CANCEL_AND_STOP = "Adios";
    public static final String AQI_LEVEL_DEFAULT = "Lo siento, no encontré datos de tu ciudad. Me puedes repetir cuál es tu ciudad si no diga salir";
    public static final String AQI_LEVEL_GOOD = "La calidad del aire en tu ciudad, es dé %s. La calidad del aire se considera satisfactoria y la contaminación del aire representa poco o ningún riesgo. No se anticipan impactos a la salud y puede realizar actividades al aire libre. Si desea conocer la calidad del aire en otra ciudad, dígala a continuación, si no, diga salir.";
    public static final String AQI_LEVEL_MODERATE = "La calidad del aire en tu ciudad, es dé %s. La calidad del aire es aceptable; sin embargo, para un número muy pequeño de personas que son inusualmente sensibles a la contaminación puede que tengan algún problema de salud. Como recomendación, los niños, adultos y las personas con enfermedades respiratorias, como el asma, deben limitar la exposición prolongada al aire libre. Si desea conocer la calidad del aire en otra ciudad, dígala a continuación, si no, diga salir.";
    public static final String AQI_LEVEL_UNHEALTHY_SENSITIVE_GROUPS = "La calidad del aire en tu ciudad, es dé %s. La calidad del aire no es saludable para personas sensible a la contaminación. Los niños, adultos y personas con enfermedades respiratorias tales como el asma, deben limitar el esfuerzo prolongado al aire libre. Si desea conocer la calidad del aire en otra ciudad, dígala a continuación, si no, diga salir.";
    public static final String AQI_LEVEL_UNHEALTHY = "La calidad del aire en tu ciudad, es dé %s. La calidad del aire es insaluble. Todos pueden comenzar a experimentar efectos en la salud; personas sensibles a la contaminación pueden experimentar efectos de salud muy graves. Los niños, adultos activos y personas con enfermedades respiratorias tales como el asma, deben evitar los esfuerzos excesivos prolongados al aire libre; Especialmente los niños, deben limitar los esfuerzos físicos excesivos y prolongados al aire libre. Si desea conocer la calidad del aire en otra ciudad, dígala a continuación, si no, diga salir.";
    public static final String AQI_LEVEL_VERY_UNHEALTHY = "La calidad del aire en tu ciudad, es dé %s. La calidad del aire es muy poco saludable. Advertencias sanitarias de condiciones de emergencia. Existe la posibilidad que la población entera se vea afectada. Los niños, adultos y personas con enfermedades respiratorias tales como el asma, deben evitar todos los esfuerzos excesivos al aire libre; Especialmente los niños, deben limitar los esfuerzos físicos al aire libre. Si desea conocer la calidad del aire en otra ciudad, dígala a continuación, si no, diga salir.";
    public static final String AQI_LEVEL_HAZARDOUS = "La calidad de aire en tu ciudad es peligrosa porque tiene un valor de %s. Alerta de salud: todos pueden experimentar efectos de salud más graves. Todos deben evitar salir al aire libre. Si desea conocer la calidad del aire en otra ciudad, dígala a continuación, si no, diga salir.";
}
